.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitbridgecoin_qt test_bitbridgecoin_qt
clean: FORCE
	$(MAKE) -C .. bitbridgecoin_qt_clean test_bitbridgecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitbridgecoin_qt_check
bitbridgecoin-qt bitbridgecoin-qt.exe: FORCE
	 $(MAKE) -C .. bitbridgecoin_qt
